//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reciclaje.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postulacion
    {
        public int idpostulacion { get; set; }
        public string tipo { get; set; }
        public string direccion { get; set; }
        public string motivo { get; set; }
    }
}
