//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reciclaje.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sugerencia
    {
        public int idSugerencia { get; set; }
        public string asunto { get; set; }
        public int fk_tema { get; set; }
        public System.DateTime fecha { get; set; }
        public string descripcion { get; set; }
    
        public virtual Tema Tema { get; set; }
    }
}
